### ISSUE TITLE
Decide on main question

### ISSUE THREAD

**Issue by casswe368** [serasoren/sds192-mp2#1]
Some ideas:

Do incumbent candidates raise more money than challenges or less? Who wins more often?

Which parties raise more money?

Which is more important, raising money or being an incumbent candidate?

Are there more challengers winning in election years than in between years?

Do Reps/Dems raise more money from committees or individuals?

**Comment by saltcrystal** [comment]
1. Do incumbents raise more money than challengers or less? => answered.
2. Do winners tend to have raised more money than losers or less? => answered. 

I think we can look at:
1. Who wins more often?
2. Which parties raise more money?
3. Do Reps/Dems raise more money from committees or individuals?

**Comment by saltcrystal** [comment]
done!
